### ISSUE TITLE
SASL extension Callback required for Confluent Cloud?

### ISSUE THREAD

**Issue by nikolai-fra** [nniikkoollaaii/workload-identity-kafka-sasl-oauthbearer#1]
https://docs.confluent.io/cloud/current/access-management/authenticate/oauth/configure-clients-oauth.html#client-login-callback-handler-top-level-configuration-options

Note the SASL extension configuration for extension_logicalCluster and extension_identityPoolId. During the OAuth token retrieval step, extensions are ignored, but will be passed to the broker using the [SASL extension mechanism from KIP-342](https://cwiki.apache.org/confluence/display/KAFKA/KIP-342%3A+Add+support+for+Custom+SASL+extensions+in+OAuthBearer+authentication).

**Comment by nniikkoollaaii** [comment]
Implemented
